'use client'
import React, { useState } from 'react'

function Home() {
  return (
    <>
    <h1>Generation Meta Data</h1>
    </>
  )
}

export default Home

// genrate metadata object 
export async function generateMetadata({ params }) {
  return {
    title: 'Hello texting',
    description: 'Generated by create next app',

  }
}